name: Stock Price Notification

on:
  schedule:
    - cron: "30 1,5 * * 1-5" # UTC 01:30 and 05:30 (13:30 CST)
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        uses: ./.github/actions/install_python_dependencies

      - name: Run stock price notification script
        env:
          STOCK_NEWS_LINE_NOTIFY_TOKEN: ${{ secrets.STOCK_NEWS_SLACK_NOTIFY_WEBHOOK }}
        run: python src/app/stock_news/stock_price_notification.py
